USE DEMO_DATABASE;
DROP TABLE "DEMO_DATABASE"."PUBLIC"."MKS_CUSTOMERS";

/* CRAETE A TABLE  */
CREATE OR REPLACE TABLE MKS_CUSTOMERS (
Customer_id int,
  Last_name varchar(50),
  First_name varchar(50),
  Birthday DATE,
  Gender varchar(10),
  participant_type varchar(50),
  Regionn_id int,
  marital_status varchar(40)
);

--- RETRIVING DATA FROM DEMO_DATABASE

SELECT * FROM MKS_CUSTOMERS;

SELECT COUNT(*) FROM MKS_CUSTOMER;
--- This customer table has 12305 nos. of records.

SELECT * FROM MKS_CUSTOMER WHERE GENDER='MALE';
--- THIS CODE SHOWS THE CUSTOMERS WHO ARE MALE 

SELECT COUNT(*) FROM MKS_CUSTOMER WHERE GENDER='MALE';
--- Total number of male customers presents in the data are 6558

DESC TABLE MKS_CUSTOMERS; --- DESCRIBE THE TABLE PROPERITES 

/* QUESTION -- WE NEED TO CREATE A AGE COLUMN ON THIS DATA */

SELECT CURRENT_DATE();
SELECT *, datediff(year,BIRTHDAY,'2022-12-25') as age FROM MKS_CUSTOMERS;


/*  we can also add a new column in atble as age by using alter table command*/
/* Modifies the properties, columns, or constraints for an existing table. */
ALTER TABLE MKS_CUSTOMERS
ADD COLUMN AGE INT;

UPDATE MKS_CUSTOMERS
SET AGE =   datediff(year,BIRTHDAY,'2022-12-25') ;


/* CREATE A NEW COL CONSIT OF FULL NAME OF CUSTOMER*/

SELECT * ,CONCAT(fIRST_NAME,' ',LAST_NAME) AS FULL_NAME  FROM MKS_CUSTOMERS;

ALTER TABLE MKS_CUSTOMERS
DROP COLUMN FULL_NAME;

ALTER TABLE MKS_CUSTOMERS
ADD COLUMN FULL_NAME VARCHAR(50);


UPDATE MKS_CUSTOMERS
SET FULL_NAME = CONCAT(fIRST_NAME,' ',LAST_NAME);

/* AS PER MARIATAL STATUS CUSTOMER SEGEMENTATION*/

SELECT DISTINCT(MARITAL_STATUS),COUNT(*) `COUNT`
 FROM MKS_CUSTOMERS
 GROUP BY MARITAL_STATUS;
 
 /* CUSTOMERS WHOSE AGE IS MORE THAN 25 AND PARTICIPATE AS INDIVISUAL*/
 SELECT COUNT(*) FROM MKS_CUSTOMERS WHERE AGE>=25;
 SELECT COUNT(*) FROM MKS_CUSTOMERS WHERE AGE>=25 AND PARTICIPANT_TYPE='INDIVIDUAL';

/* GROUP BY PARTCIPANT TYPE TO KNOW THE COUNT */
SELECT DISTINCT(PARTICIPANT_TYPE),COUNT(*) COUNT 
FROM MKS_CUSTOMERS
GROUP BY PARTICIPANT_TYPE ;
